# Generated by Django 5.0.2 on 2024-02-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_userforum_role_userforum_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userforum',
            old_name='group',
            new_name='groupe',
        ),
    ]
