# Generated by Django 5.0.2 on 2024-02-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonbb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pythonbb/images/'),
        ),
    ]
