# Generated by Django 5.0.2 on 2024-02-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonbb', '0002_forum_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pythonbb/static/pythonbb/images/'),
        ),
    ]
